---
- name: Configure interfaces and routes on six PCs.
  hosts: pcs # Target the group containing the PCS
  gather_facts: false
  tasks:
    - name: Print some facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Check if IP address "{{ item.address }}" exists on "{{ item.name }}"
      ansible.builtin.command:
        argv:
          - /bin/sh
          - -c
          - >
            ip addr show dev {{ item.name }}
            | grep -q -w {{ item.address }}
            || ip addr add {{ item.address }}/{{ item.prefix}} dev {{ item.name }}
      loop: "{{ interface_ips }}"
      loop_control:
        label: "{{ item.name }} -> {{ item.address }}"

    - name: Check if Route "{{ item.route }}" via "{{ item.gateway }}" exists
      ansible.builtin.command:
        argv:
          - /bin/sh
          - -c
          - >
            ip route
            | grep -q -w {{ item.route }}
            || ip route add {{ item.route }} via {{ item.gateway }}
      loop: "{{ interface_ips }}"
      loop_control:
        label: "{{ item.route }} -> {{ item.gateway }}"
